# Site settings
title: Around DH in 80 Days 
email: colibri.alex@gmail.com
description: "This work is licensed under a <a rel=&#39;license&#39; href=&#39;http://creativecommons.org/licenses/by/3.0/us/&#39;>Creative Commons Attribution 3.0 United States License</a>."
baseurl: ""
url: "http://www.arounddh.org"

# Build settings
markdown: kramdown
permalink: pretty

# For documentation purposes
timezone: America/New_York