# Site settings
title: Around DH in 80 Days 
email: colibri.alex@gmail.com
description: "A tour of the digital humanities in 80 days"
baseurl: ""
url: "http://www.elotroalex.com"

# Build settings
markdown: kramdown
permalink: pretty

# Paginator
paginate: 81

# Stop future posts from publishing
future: false

limit_posts: 1

timezone: America/New_York