# Site settings
title: Around DH in 80 Days 
email: colibri.alex@gmail.com
description: "A tour of the digital humanities in 80 days"
baseurl: ""
url: "http://www.elotroalex.com"

# Build settings
markdown: kramdown
permalink: pretty

# For documentation purposes
timezone: America/New_York